# Limei by harunnoir
# SPDX-License-Identifier: GPL-3.0-or-later
# Colors: CC-BY-SA-4.0

# Optional starting configuration. Adjust the font and padding to your setup.
include=~/.config/foot/themes/limei.ini

font=monospace:size=11
pad=8x8
dpi-aware=yes
term=xterm-256color
selection-target=primary
locked-title=no

[scrollback]
lines=10000
multiplier=3.0

[mouse]
hide-when-typing=yes

[cursor]
style=block
blink=no
