# Limei by harunnoir
# SPDX-License-Identifier: GPL-3.0-or-later
# Colors: CC-BY-SA-4.0

set -g status-style "bg=#101010,fg=#837f78"

set -g pane-border-style "fg=#393632"
set -g pane-active-border-style "fg=#9a897c"

setw -g window-status-style "bg=#101010,fg=#64605a"
setw -g window-status-current-style "bg=#101010,fg=#c0bbb3,bold"
setw -g window-status-activity-style "bg=#101010,fg=#788184"
setw -g window-status-bell-style "bg=#101010,fg=#9a7477,bold"

set -g message-style "bg=#171717,fg=#ada9a3"
set -g message-command-style "bg=#171717,fg=#9a897c"
setw -g mode-style "bg=#292724,fg=#c0bbb3,bold"

set -g display-panes-colour "#64605a"
set -g display-panes-active-colour "#7f8c77"
setw -g clock-mode-colour "#97916f"

set -g menu-style "bg=#171717,fg=#ada9a3"
set -g menu-selected-style "bg=#302d29,fg=#c0bbb3,bold"
set -g menu-border-style "fg=#393632"

set -g popup-style "bg=#171717,fg=#ada9a3"
set -g popup-border-style "fg=#788184"
