# Limei by harunnoir
# SPDX-License-Identifier: GPL-3.0-or-later
# Colors: CC-BY-SA-4.0

background-color=#171717
text-color=#ada9a3
border-color=#9a897c
progress-color=over #768569

width=360
height=120
margin=12
padding=12
border-size=1
border-radius=5

font=monospace 10
default-timeout=5000
layer=overlay
anchor=top-right

[urgency=low]
border-color=#788184
text-color=#837f78

[urgency=normal]
border-color=#9a897c

[urgency=high]
border-color=#9a7477
text-color=#c0bbb3
default-timeout=0
