# Limei by harunnoir
# SPDX-License-Identifier: GPL-3.0-or-later
# Colors: CC-BY-SA-4.0

theme[main_bg]="#101010"
theme[main_fg]="#ada9a3"
theme[title]="#c0bbb3"
theme[hi_fg]="#9a897c"
theme[selected_bg]="#292724"
theme[selected_fg]="#c0bbb3"
theme[inactive_fg]="#64605a"
theme[graph_text]="#837f78"
theme[meter_bg]="#393632"
theme[proc_misc]="#898661"

theme[cpu_box]="#9a7869"
theme[mem_box]="#8d818a"
theme[net_box]="#788184"
theme[proc_box]="#7f8c77"
theme[div_line]="#393632"

theme[temp_start]="#768569"
theme[temp_mid]="#a38762"
theme[temp_end]="#9a7477"

theme[cpu_start]="#768569"
theme[cpu_mid]="#97916f"
theme[cpu_end]="#9a7477"

theme[free_start]="#768569"
theme[free_mid]="#7f8c77"
theme[free_end]="#788184"

theme[cached_start]="#788184"
theme[cached_mid]="#8d818a"
theme[cached_end]="#9a7869"

theme[available_start]="#768569"
theme[available_mid]="#7f8c77"
theme[available_end]="#97916f"

theme[used_start]="#97916f"
theme[used_mid]="#9a7869"
theme[used_end]="#9a7477"

theme[download_start]="#788184"
theme[download_mid]="#7f8c77"
theme[download_end]="#768569"

theme[upload_start]="#8d818a"
theme[upload_mid]="#9a7869"
theme[upload_end]="#a38762"

theme[process_start]="#7f8c77"
theme[process_mid]="#97916f"
theme[process_end]="#9a7869"
